/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        "tertiary-fixed-dim": "#c1c7cf",
        "primary": "#b7c4ff",
        "on-surface-variant": "#c3c5d9",
        "secondary-container": "#c3f400",
        "secondary": "#ffffff",
        "surface-container-low": "#1c1b1b",
        "inverse-surface": "#e5e2e1",
        "on-tertiary": "#2b3137",
        "tertiary": "#c1c7cf",
        "on-error-container": "#ffdad6",
        "inverse-primary": "#004ced",
        "secondary-fixed-dim": "#abd600",
        "on-secondary": "#283500",
        "primary-fixed-dim": "#b7c4ff",
        "on-primary": "#002682",
        "error": "#ffb4ab",
        "surface-variant": "#353534",
        "background": "#131313",
        "on-tertiary-container": "#e0e6ee",
        "on-surface": "#e5e2e1",
        "on-background": "#e5e2e1",
        "outline-variant": "#434656",
        "inverse-on-surface": "#313030",
        "on-secondary-container": "#556d00",
        "surface-dim": "#131313",
        "on-error": "#690005",
        "surface-container-highest": "#353534",
        "on-tertiary-fixed-variant": "#41474e",
        "outline": "#8d90a2",
        "on-primary-fixed-variant": "#0038b6",
        "secondary-fixed": "#c3f400",
        "surface-tint": "#b7c4ff",
        "on-secondary-fixed-variant": "#3c4d00",
        "on-primary-container": "#dfe3ff",
        "tertiary-container": "#60676e",
        "on-primary-fixed": "#001452",
        "error-container": "#93000a",
        "tertiary-fixed": "#dde3eb",
        "surface-container-high": "#2a2a2a",
        "surface": "#131313",
        "primary-container": "#0052ff",
        "surface-container": "#201f1f",
        "on-tertiary-fixed": "#161c22",
        "surface-container-lowest": "#0e0e0e",
        "surface-bright": "#393939",
        "primary-fixed": "#dde1ff",
        "on-secondary-fixed": "#161e00"
      },
      borderRadius: {
        "DEFAULT": "0.25rem",
        "lg": "0.5rem",
        "xl": "0.75rem",
        "full": "9999px"
      },
      spacing: {
        "unit": "4px",
        "container-max": "1280px",
        "gutter": "16px",
        "gutter-desktop": "24px",
        "margin-desktop": "40px",
        "margin-mobile": "20px"
      },
      fontFamily: {
        "body-lg": ["Inter"],
        "body-md": ["Inter"],
        "display-lg": ["Barlow Condensed"],
        "display-xl": ["Barlow Condensed"],
        "label-caps": ["JetBrains Mono"],
        "display-lg-mobile": ["Barlow Condensed"],
        "headline-lg": ["Barlow Condensed"],
        "headline-lg-mobile": ["Barlow Condensed"],
        "headline-md": ["Barlow Condensed"],
        "headline-sm": ["Barlow Condensed"]
      },
      fontSize: {
        "headline-lg": ["clamp(36px, 5vw, 48px)", {"lineHeight": "1.1", "letterSpacing": "-0.01em", "fontWeight": "700"}],
        "body-md": ["16px", {"lineHeight": "1.5", "fontWeight": "400"}],
        "label-caps": ["12px", {"lineHeight": "1.0", "letterSpacing": "0.1em", "fontWeight": "600"}],
        "headline-md": ["clamp(24px, 4vw, 32px)", {"lineHeight": "1.2", "fontWeight": "700"}],
        "body-lg": ["clamp(16px, 2vw, 18px)", {"lineHeight": "1.5", "fontWeight": "400"}],
        "headline-sm": ["clamp(20px, 3vw, 24px)", {"lineHeight": "1.2", "fontWeight": "600"}],
        "display-xl": ["clamp(48px, 8vw, 72px)", {"lineHeight": "1.0", "letterSpacing": "-0.02em", "fontWeight": "800"}],
        "display-lg": ["clamp(48px, 5vw, 64px)", {"lineHeight": "1.1", "letterSpacing": "-0.02em", "fontWeight": "700"}],
        "headline-lg-mobile": ["clamp(28px, 4vw, 36px)", {"lineHeight": "1.1", "fontWeight": "700"}]
      }
    },
  },
  plugins: [],
}
