CREATE DATABASE IF NOT EXISTS stadiumiq;
USE stadiumiq;

CREATE TABLE IF NOT EXISTS users (
  id INT AUTO_INCREMENT PRIMARY KEY,
  email VARCHAR(255) NOT NULL UNIQUE,
  password_hash VARCHAR(255) NOT NULL,
  username VARCHAR(100) NOT NULL UNIQUE,
  role VARCHAR(50) DEFAULT 'fan',
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);
